name: Render R Markdown and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - '**.Rmd'   # Solo se activa si cambias un archivo Rmd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr"))'

      - name: Render R Markdown
        run: |
          Rscript -e 'rmarkdown::render("index.Rmd", output_file = "docs/index.html")'

      - name: Commit and push rendered HTML
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add docs/index.html
          git commit -m "Auto-update HTML from Rmd" || echo "No changes to commit"
          git push
